apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-backend
  namespace: tienda-perritos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tienda-backend
  template:
    metadata:
      labels:
        app: tienda-backend
    spec:
      containers:
      - name: backend
        image: 901485029489.dkr.ecr.us-east-1.amazonaws.com/tienda-backend
        ports:
        - containerPort: 3000 
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: DB_HOST
          value: "mysql-service" 
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tienda-secrets
              key: db-root-password
        - name: DB_NAME
          value: "tienda_perritos"
        - name: PORT
          value: "3000" # Cambiado a 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: tienda-perritos
spec:
  selector:
    app: tienda-backend
  ports:
    - protocol: TCP
      port: 3000 # Cambiado a 3000
      targetPort: 3000