apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-db
  namespace: tienda-perritos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tienda-db
  template:
    metadata:
      labels:
        app: tienda-db
    spec:
      containers:
      - name: mysql
        # Usamos la imagen oficial minimalista como buena práctica
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tienda-secrets
              key: db-root-password
        - name: MYSQL_DATABASE
          value: "tienda_perritos"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: tienda-perritos
spec:
  selector:
    app: tienda-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306