apiVersion: v1
kind: Secret
metadata:
  name: tienda-secrets
  namespace: tienda-perritos
type: Opaque
stringData:
  # Esto es un comodín que el pipeline reemplazará
  db-root-password: REPLACE_ME_PASSWORD