apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tienda-perritos
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASSWORD: "REPLACE_ME_PASSWORD"
  DB_DATABASE: "tienda_perritos"