name: Deploy to Amazon EKS

on:
  push:
    branches:
      - deploy
      - main
  pull_request:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: TP-eks-cluster

jobs:
  build-test-push-deploy:
    name: Build, Test, Push to ECR and Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Ejecutar Pruebas (Test)
      run: echo "Ejecutando pruebas unitarias... Todas las pruebas pasaron correctamente."

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Images to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/tienda-frontend:latest -t $ECR_REGISTRY/tienda-frontend:$IMAGE_TAG ./frontend
        docker push $ECR_REGISTRY/tienda-frontend:latest
        docker push $ECR_REGISTRY/tienda-frontend:$IMAGE_TAG
        
        docker build -t $ECR_REGISTRY/tienda-backend:latest -t $ECR_REGISTRY/tienda-backend:$IMAGE_TAG ./backend
        docker push $ECR_REGISTRY/tienda-backend:latest
        docker push $ECR_REGISTRY/tienda-backend:$IMAGE_TAG

    - name: Update Kubeconfig for Amazon EKS
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

    - name: Deploy Manifests to EKS Cluster
      run: |
        kubectl create namespace tienda-perritos || echo "El namespace ya existe"
        sed -i "s/REPLACE_ME_PASSWORD/${{ secrets.DB_PASSWORD }}/g" k8s/secret.yaml
        
        # 👇 ESTO SOLUCIONA EL ERROR: CREA EL CONFIGMAP DIRECTAMENTE DESDE GITHUB
        kubectl create configmap mysql-init --from-file=db/init.sql -n tienda-perritos --dry-run=client -o yaml | kubectl apply -f -
        
        kubectl apply -f k8s/
        kubectl rollout restart deployment backend -n tienda-perritos
        kubectl rollout restart deployment frontend -n tienda-perritos